ALTER TABLE appointment
    MODIFY COLUMN status ENUM('PENDING', 'APPROVED', 'REJECTED', 'FINISHED') DEFAULT 'PENDING',
    ADD COLUMN finished_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN description VARCHAR(255) NULL,
    ADD COLUMN reject_comment VARCHAR(255) NULL,
    ADD COLUMN picture LONGBLOB NULL;
